# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline for Hugging Face Spaces

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the type of runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Specifies Python 3.10

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip # Path to cache pip dependencies
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} # Cache key based on OS and requirements.txt
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Installs dependencies from requirements.txt

      - name: Run tests
        run: |
          pip install pytest # Installs pytest
          pytest tests/ # Runs tests located in the tests/ folder

      - name: Log in to Hugging Face Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.hf.space
          username: ${{ github.repository_owner }} # Uses the repository owner's username
          password: ${{ secrets.HF_TOKEN }} # Uses the HF_TOKEN secret for authentication

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Docker build context
          push: true # Pushes the image after building
          tags: registry.hf.space/atipan01/your-space-name:latest # Tags the image for Hugging Face Spaces

      - name: Simulate local run (optional)
        run: |
          echo "Simulating local run of main.py..."
          # Ensure your Docker container runs main.py or adjust this step
          # For example, if your Dockerfile's CMD is `python main.py`
          # then the deployed space will run it.
          # This step is more for local validation if needed.
          # If you want to run main.py directly in the CI environment:
          # python main.py
          echo "Local run simulation complete."

      - name: Show status message - Deployment
        run: echo "Deployment to Hugging Face Space initiated."
